version: "3"

services:
  embrace_db:
    image: postgres:13.0
    container_name: embrace-db2
    restart: always
    privileged: true
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: ${PG_DATA}
    volumes:
      - ${PG_VOLUME}:${PG_DATA}

  rabbitmq:
    image: rabbitmq:3.8.8-management
    container_name: embrace-mq
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
    ports:
      - "15672:15672"

  scheudler:
#    image: wangyuefei/icm-scripts-scheduler:2.0
    image: embrace/icm-scheduler:2.0
    container_name: embrace-icm-scheduler
    environment:
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PORT: ${PG_PORT}
      PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - embrace_db
      - rabbitmq

